### ISSUE TITLE
Md5 Checksum?

### ISSUE THREAD

**Issue by daniel-leal** [refile/refile#159]
Hi, I want check the md5 to prevent the repeated uploads, but I doesn't see anything like it on refile. Any sugestions?

**Comment by jnicklas** [comment]
Do you mean as in hashing files by content, rather than randomly, so that if the same file is uploaded multiple times, it won't take up more space?

First of all do NOT use md5 for this purpose!!! Read [this blog post](http://natmchugh.blogspot.se/2014/10/how-i-created-two-images-with-same-md5) for the scary details as to why not. md5 is not secure anymore.

My guess would be that you'd want something like HMAC-SHA1 or something if you want to do this, but please don't listen to me, I'm not a crypto expert. Getting this right is much, much harder than simply choosing a random number as the ID.

Also Refile does not support this. There are indications in the codebase that it would, but this is actually something that's been bothering me for a while, and I'll likely change it.

The problem mainly comes from deleting files. It is much harder to track if a file should be deleted if there might be multiple references to it. Essentially you'll have to reference-count the files, which is just not something that Refile's backends are designed to do. (though it would be entirely possible to write a backend which does this).
