### ISSUE TITLE
Sinatra application streaming always returning Content-Type 'application/octet-stream'

### ISSUE THREAD

**Issue by mackermedia** [refile/refile#160]
First of all, thanks for the hard work on Carrierwave and Refile. Carrierwave has been great in the past, and I'm looking forward to the benefits of a newer library incorporating lessons learned.

Now to the issue:

* * *

I've used the default instructions on setting up refile on a new Rails app. (Example app can be found [here](https://bitbucket.org/mackermedia/refile_content_type_test)).

It looks like the Sinatra app is failing to accurately determine `Content-Type`. I've even tried adding the `attachment_name_content_type` column to my Model and can see that it is correctly storing that value in the database.

After a little debugging, it looks like the Sinatra app is trying to determine the Content-Type by looking at `::File.extname(request.path)` (https://github.com/elabs/refile/blob/master/lib/refile/app.rb#L106), and since refile uses tokens for path names and not the actual filename, the extension is `""`. 

Example:
![](http://monosnap.com/image/WSWZbF5b3CisFHJvRVBlf6TSkeYQoq.png)

This results in a Content-Type of `application/octet-stream`. This is preventing IE9 from properly displaying images.

Example: 
![](http://monosnap.com/image/UMPHbqzoQindJLtlFZg4vfSOiYxtG6.png)

It looks like it might take a significant refactoring to be able to get ahold of the ActiveRecord object from within the Sinatra app in order to be able to use the stored `image_content_type` or even look at the original filename.

If you can point me in the right direction, I'd be happy to attempt a fix.

**Comment by jnicklas** [comment]
Unfortunately the README doesn't explain very well how this is *supposed* to work. I'll see if I can work this into the docs somehow.

Basically, the Sinatra app should not be aware of anything to do with the model, or the data that was stored in it. But we still want to serve the file with the appropriate content-type. What we do is specify the content-type in the URL instead, via the file extension. So we want a URL like:

```
/attachments/store/xyz/image.png
```

This way, Sinatra can infer that this is a PNG file and serve it with the appropriate content type.

Unfortunately the URL in your case did not include the file extension. There are three ways a URL can get an extension:

1. It's explicitly set. As in `attachment_url(..., format: "jpg")`. The image processing system will actually use this information to convert to the appropriate format automatically.
2. It is inferred from the stored content type
3. It is taken from the stored filename

My guess as to what went wrong in your case is that while you added the  `attachment_name_content_type` column, you did not retroactively add data to the files that had already been uploaded without a content type, and so the already uploaded files did not have a content type, and therefore no extension in the URL. Am I right?

I've already tweaked the quick start example to suggest option (1) for now, and I'll work on further improving the documentation so that this doesn't trip up more people.

**Comment by mackermedia** [comment]
Thanks for the excellent response!

I actually tried the `attachment_name_content_type` and it was failing for new records, so I don't think that was the specific issue. It seems the Sinatra app wasn't inferring it from the stored content type (since it doesn't have access to the model).

This makes a lot more sense now and I'll go ahead and update my attachment_url or update the way the file URL is stored. 

You can consider this closed from my end. I've verified that supplying the format like `attachment_url(..., format: "jpg")` does indeed fix my problem.
