### ISSUE TITLE
Client side validation on direct upload

### ISSUE THREAD

**Issue by activestylus** [refile/refile#172]
One of my fave features of refile is the direct upload magic that happens on file input change.

Trying to figure out how I can inject a callback somehow to simply check the file extension before the auto-upload even happens, and warn user of bad file types on the client (server side is already validated).

Any ideas?

**Comment by jnicklas** [comment]
Well, it already sets up the `accept` attribute for the file input automatically for you, which means that in browsers where it's supported (IE8+ and oddly enough *not* in Safari), will not allow you to upload a file with an invalid type in the first place. I think this is the nicer way of handling this, and since it's more of a convenience/perf feature, I'm personally okay with this not working for some people.

**Comment by activestylus** [comment]
I agree that's the best way to handle it. Incidentally I was using Safari and that's probably why it wasn't working (it is SUPER bizarro that IE8 works better)

I will probably write my own quick and dirty polyfill as Safari users are a significant chunk of our userbase. Thanks for the clarification!

**Comment by acrogenesis** [comment]
I know this is old but @activestylus did you find a way to solve it for safari users?
