### ISSUE TITLE
Refile.attachment_url generates invalid URLs when using Cloudfront

### ISSUE THREAD

**Issue by lserman** [refile/refile#173]
This is my first time setting up Cloudfront with Refile so it may be a simple mistake. I am transcoding some videos in a background job and then setting them like this:

```ruby
File.open(@mp4_path) { |file| record.video_mp4 = file }
record.save
```

The first issue I had was that Refile was prefixing generated URL's with "attachments/" by default, I assume this is because I am requiring refile/rails? 

I had to add "attachments/" to the prefix here so that it would upload them to an "attachments" directory in s3, but I would like a cleaner solution.

`Refile.store = Refile::Backend::S3.new(prefix: 'attachments/store', **aws)`

The second issue is that the generated URLs are suffixed with the attachment name, so my URLs are like:

`//abcdef.cloudfront.net/attachments/store/{ID}/video_mp4`

The files are actually being stored at:

`//abcdef.cloudfront.net/attachments/store/{ID}`

Is there a way I can upload with that suffix? Most of my config is the stuff provided in the README:

```ruby
aws = {
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
  bucket: ENV['AWS_S3_BUCKET_NAME'],
}

Refile.cache = Refile::Backend::FileSystem.new('/tmp')
Refile.store = Refile::Backend::S3.new(prefix: 'attachments/store', **aws)
Refile.host = "//abcdef.cloudfront.net"
```

When I drop the /video_mp4 suffix and use the attachments/ prefix, everything works great.

**Comment by jnicklas** [comment]
This isn't really the recommended way of setting up Refile. The idea is to have the CDN in front of your app, and have Refile serve the files from your application, not setting the CDN in front of S3. With video files, even that initial hit might be large, so that might not be what you want. But this is the way it's meant to be used. The URL generated by `attachment_url` is not meant to match the path where the file is stored on S3. In fact, you'll notice that the next version of Refile will include a token in that URL which is essentially random and unpredictable.

If you want to generate files to a CDN in front of S3 you should *not* use the `attachment_url` helper or `Refile.attachment_url`. You should be generating the URLs manually.

**Comment by lserman** [comment]
I see. I think for this specific use case, manually generating the URL will make the most sense since I'm not doing any on the fly processing of videos, I'm doing it on my own in a background job.

A bit off topic, but how would this work with S3 if I were to be serving images that are processed on the fly? If the CDN is in front of the app but the images are stored on S3, is it still possible to process them?

**Comment by jnicklas** [comment]
Yes, this is precisely why we do it this way. The app downloads the file from S3, resizes it and serves up the result.

**Comment by lserman** [comment]
I gotcha, so it goes Cloudfront -> Rails app -> Attachments engine -> stream from S3, process. Then it's on Cloudfront after that.

**Comment by bobbytables** [comment]
I opened a ticket because of this confusion, might be good to update the README to explain this. It's pretty common to have S3 as the origin of files.
