### ISSUE TITLE
0 file size

### ISSUE THREAD

**Issue by bmsolutions** [refile/refile#200]
While using the file system backend I keep getting an empty file when getting the file from the download link. Upload works fine. 

In my document create method:
backend = Refile::Backend::FileSystem.new("tmp")
file = backend.upload(params["document"]["document"].tempfile)

The download link: http://0.0.0.0:3000/attachments/store/9b9624a7e87696793548d2c4a539a55f97e6253fe02dd64e52b43a9a4760/VERSION

**Comment by janko-m** [comment]
Could you provide a complete code snippet that fails (produces an empty file)?

**Comment by bmsolutions** [comment]
The link is produced via: link_to document.file_name,
attachment_url(document, :document, filename: document.file_name)

The link then opens an empty file.

Is this what you are looking for? All I'm trying to do right now is a
simple upload and retrieval.

Thanks,
Benny Rosenberger
CTO
Benchmark Merchant Solutions
718-506-9212

**Comment by bmsolutions** [comment]
Any updates? 

BTW, downloading from S3 works fine.

**Comment by janko-m** [comment]
What does `params[:document][:document].tempfile.read` return? Is the uploaded file blank, or just when you download it. You can just pass in `params[:document][:document]` directly, maybe that will help.

It would really help us if you could try to isolate the failure by creating a plain Ruby file which we can run, and see that indeed a blank file is generated. Because we can't know how your application is set up, and by isolating we can determine where could the error be. Otherwise you are the only person that can debug it.

**Comment by bmsolutions** [comment]
params[:document][:document].tempfile is the uploaded file which gets uploaded fine. I can open the uploaded file in the tmp directory.

Ok. I solved it once I added the following to the refile initializer:
require "refile/backend/file_system"

Refile.cache = Refile::Backend::FileSystem.new("tmp")
Refile.store = Refile::Backend::FileSystem.new("tmp")

**Comment by rilian** [comment]
I had the same issue with 0 bytes downloads, but the issue root was that `cancancan`'s `load_and_authorize_resource` in `AttachmentsController` somehow conflicted with Refile routes to download `Attachments` (ActiveRecord model in my application). 

Fixed by not using `load_and_authorize_resource` on the routes that are shared with Refile routes.
