### ISSUE TITLE
Built-in #to_url

### ISSUE THREAD

**Issue by dhyegofernando** [refile/refile#208]
Hi,

I was looking for to how to build my own attachment URL, and them I opened this [file](https://github.com/refile/refile/blob/master/lib/refile/rails/attachment_helper.rb) and I figured out how to do this:

```ruby
user = User.last
user.profile_image # #<Refile::File:0x007f99fe2073b8...>
user.profile_image_filename # 23374_418505028243167_332794789_n.jpg

Refile.attachment_url user, :profile_image # /attachments/store/*****/23374_418505028243167_332794789_n.jpg
```

Ok, it worked but what about do something like this:

```ruby
user = User.last
user.profile_image_url # /attachments/store/*****/23374_418505028243167_332794789_n.jpg

# either with options
user.profile_image_url filename: 'abc.jpg' # /attachments/store/*****/abc.jpg
```

It would be pretty nice. :+1: 

What about it?

**Comment by jnicklas** [comment]
It used to be that we actually took into account request-specific information in the helper, which is why we made it a helper. But we don't do that anymore, so this is really something we could do. Should we though? I like that there's a symmetry between `attachment_url`, `attachment_image_tag` and `attachment_field`. Maybe that's a silly argument which is outweighed by making access of the URL much more convenient. I'm not sure.

**Comment by dhyegofernando** [comment]
That's a matter of necessity. I will explain to you... I'm building an REST API so I need to answer an image uploaded giving its URL. It could be pretty useful if would exist a shortcut doing this with a Model method like I mentioned above, couldn't it?

**Comment by jnicklas** [comment]
@janko-m what do you think about this one?

**Comment by janko-m** [comment]
Well, I'm generally always for adding as few methods to ActiveRecord objects as possible, but on the other hand it is convenient as a shorthand, especially for APIs. I vote :+1: for this feature.

**Comment by dhyegofernando** [comment]
Nice.

**Comment by jnicklas** [comment]
Done.

**Comment by dhyegofernando** [comment]
:raised_hands:
