### ISSUE TITLE
Getting S3 URLs

### ISSUE THREAD

**Issue by sthapit** [refile/refile#240]
Is it possible to get S3 URLs for attachments?  We have user uploaded images that cache nicely with a CDN.  But we also have user uploaded files that don't need to be cached and it makes more sense to give them a direct S3 URL instead of using send_file to stream the file through the app.  The files are already uploaded to S3 and we have the IDs so it should be possible to get their authenticated S3 URLs?

**Comment by jnicklas** [comment]
Currently all files are streamed through the app. This is something we might work on as part of #229, but it's not yet clear what the solution will be. It is quite wasteful to stream files which are accessible through S3 from the app. On the other hand, blindly doing a redirect will kill performance when we do run through a CDN (since most CDNs don't follow redirects).

**Comment by abitdodgy** [comment]
Is it not possible to store the S3 URL and add it to the form when doing direct/presigned uploads?

**Comment by abevoelker** [comment]
This would be really nice to have! I was getting excited about switching over from CarrierWave so that I could stop being pinned to an old version of mini_magick and unload my bag of monkeypatches, but this is a dealbreaker for me.

I appreciate the effort so far though, everything looks really clean. Let me know if you need any volunteer help when implementing a solution for this.

**Comment by famousky** [comment]
+1

**Comment by geetfun** [comment]
Perhaps this could be an add on to the attachment_url method?

eg. attachment_url(:photo, :resource, s3_url: true)

**Comment by ivobenedito** [comment]
+1

**Comment by stephendolan** [comment]
+1

**Comment by mandrews** [comment]
+1

**Comment by causztic** [comment]
same here, in the midst of changing over from carrierwave and would like this feature too.

**Comment by abitdodgy** [comment]
@callmeed why not have a background job that adds this to a db column, that way it's available when you need it? Or is it a security issue?

**Comment by callmeed** [comment]
@abitdodgy well, the URL will eventually expire ... so I'd have to keep track of that and update the DB record before. If I'm going to do that, I'd probably just use my Redis-backed Rails cache. 

Not a security issue for me as I'm just using it for images.

**Comment by jnicklas** [comment]
Solving this is basically solving #229, so I'll close this in favour of #229, which has more information about the various tradeoffs involved.

It's good to keep in mind that S3 cannot process your files, which is the major reason the setup is at is is.
