### ISSUE TITLE
Uninitialized constant Refile::Backend::S3::AWS

### ISSUE THREAD

**Issue by maxcodes** [refile/refile#258]
Upgraded to 0.5.5 and got this error when running `rails server`
```
/Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/refile-0.5.5/lib/refile/backend/s3.rb:37:in `initialize': uninitialized constant Refile::Backend::S3::AWS (NameError)
        from /Users/max/Sites/beek_core/config/initializers/refile.rb:9:in `new'
        from /Users/max/Sites/beek_core/config/initializers/refile.rb:9:in `<top (required)>'
        from /Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:648:in `block in load_config_initializer'
        from /Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in `instrument'
        from /Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:647:in `load_config_initializer'
        from /Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
        from /Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:611:in `each'
        from /Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/engine.rb:611:in `block in <class:Engine>'
        from /Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `instance_exec'
        from /Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `run'
        from /Users/max/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `block in run_initializers'
 ```

(let me know if you need the rest of the stack trace)

Here's my initializer:

```ruby
# config/initializers/refile.rb
require "refile/backend/s3"

aws = {
  access_key_id: ENV['AWS_ACCESS_KEY_ID'],
  secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
  bucket: ENV['S3_BUCKET_NAME']
}
Refile.cache = Refile::Backend::S3.new(prefix: "cache", **aws)
Refile.store = Refile::Backend::S3.new(prefix: "store", **aws)
Refile.host = ENV['CDN_HOST']
```

**Comment by senorprogrammer** [comment]
Just to rule this out, do you have the aws-sdk gem defined in your Gemfile?

**Comment by maxcodes** [comment]
@senorprogrammer yes!

**Comment by jnicklas** [comment]
I'd expect to see this kind of error if you're running aws-sdk >= 2.0.0. But you don't seem to be using that, so I don't know. Refile is so far only compatible with aws-sdk 1.x, though you can use the new `refile-s3` gem instead of the built in backend if you need aws-sdk 2.

One possible problem could be that I don't think you should be running aws-sdk < 2.0.0 and aws-sdk-v1 at the same time. The idea of aws-sdk-v1 is that you should be using it alongside aws-sdk 2. It's possible they conflict somehow.

**Comment by maxcodes** [comment]
I just rolled back to refile 0.5.3 and the error went away. Checked the Gemfile.lock and the `aws-sdk` gems are all the same version. Weird.

**Comment by jnicklas** [comment]
Pretty sure this is due to some kind of version breakage with `aws-sdk`. The change from 0.5.3 to 0.5.4 is minimal, and nothing about it touches aws. See: https://github.com/refile/refile/compare/v0.5.3...v0.5.4.

That being said, you should **definitely** make sure to upgrade to 0.5.4. Run `bundle update refile` so as not to change the version of aws-sdk. The security issue discovered in 0.5.1-3 that 0.5.4 fixes is very, very severe. You should not be running version 0.5.3.

**Comment by maxcodes** [comment]
I'll close this since a fresh reinstall cleared the problem. On 0.5.5 now.
