### ISSUE TITLE
Images stored on Amazon AWS S3 not rendered in Internet Explorer

### ISSUE THREAD

**Issue by acandael** [refile/refile#272]
or my AdLit web application, I store some images on Amazon AWS S3. But these images don't get rendered in any version of Internet Explorer (tested with IE8, IE9 and IE11)

you can check this out on:

http://www.adlit.be/team

The images get rendered in Safari, Firefox and Chrome, but not in Internet Explorer.

I posted this issue also on Stack Overflow:

http://stackoverflow.com/questions/29298313/images-stored-on-amazon-aws-s3-not-rendered-in-internet-explorer

Someone told me that is is problem is due to the content type:

application/octet-stream

that is set in the content header.

Is anyone familiar with this problem?

greetings,

Anthony

**Comment by jnicklas** [comment]
You should make sure the files have the right extension when requested. There are three ways of doing this:

1) Store the filename
2) Store the content type
3) Specify an explicit format when generating a link.

In order to do 1) or 2), all you need to do is add a column to your model and it will be filled in with the right data. See the README for details.

For option 3) you should just do something like:

``` ruby
attachment_url(@post, :image, format: "jpg")
```

This will always set the extension to `jpg`. This is obviously less flexible if you're not sure what kind of file you're dealing with. Especially with images you might want to allow multiple formats. In that case, option 2) is better.

(The quick start guide in the README uses option 3, just fyi).

**Comment by acandael** [comment]
Hi jnicklas, sorry for my late response. I used solution 2) that you suggested, and this fixed the issue.

I added a image_content_type column to my members table and now images stored on Amazon S3 are also showing up in Internet Explorer.

Thanks a lot,

Anthony

**Comment by jd1386** [comment]
Hi,
I'm having the same issue here, too. So I'll be trying solution (2) above soon but I already have a bunch of records without the content type string column. What would you suggest to fill existing records' content type string columns?
