### ISSUE TITLE
Question about Multiple File Uploads

### ISSUE THREAD

**Issue by ZempTime** [refile/refile#274]
I'm confused on how to set up multiple file uploads to one model.

```
class Image < ActiveRecord::Base
  attachment :file
end
```

```
  <%= form_for @image do |f| %>
    <%= f.attachment_field :file, multiple: true, direct: true, presigned: true %>

    <%= f.button "Submit", class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Saving..."} %>
  <% end %>
```

I can upload singular images (to S3) fine - but I'd like to be able to upload/create multiple @image's without needing to create an association that nests them.

What I'm confused on is how I need to set up my controller, define my params, change the activerecord macro or what exactly I need to do to make this happen. I would put them here but I'm throwing an error immediately in my images#create action, and its not even reaching there. As a result, I've been reading around through the source, but still don't understand what information is being sent where, how, so figured it was time to ask.

Whenever I try to upload more than one, I get:

```
Rack::Utils::ParameterTypeError: expected Array (got String) for param `file'
~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/utils.rb:141:in `normalize_params'
~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/utils.rb:155:in `normalize_params'
~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/multipart/parser.rb:76:in `block (2 levels) in parse'
~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/multipart/parser.rb:249:in `get_data'
~/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/multipart/parser.rb:73:in `block in parse'
etc
```

And if worse comes to worse, I could just create an ImageUpload model to follow along with the readme, but figured I'd ask!

**Comment by jnicklas** [comment]
The attachment field will be submitted as an array of file, you need to permit it as such. For example:

``` ruby
params.require(:image).permit(file: [])
```

Rails is pretty strict about this. Be aware thought that Refile is not set up to be used like this. Assigning an array to an attachment field will raise an error. This leaves you two options:

1) Use `accepts_attachments_for` and set up an association and store the files there.
2) Handle the persistence of files yourself. This is pretty tricky, since the format that the files are sent in with `multiple: true` is pretty strange (and also possibly subject to change). I would not recommend this approach unless you have a decent understanding of how Refile works internally. It might help to read this: https://github.com/refile/refile/blob/master/lib/refile/attachment/active_record.rb#L96-L114
