### ISSUE TITLE
Issues when creating multiple images with nested_attributes

### ISSUE THREAD

**Issue by tomciopp** [refile/refile#282]
I need to be able to create multiple attachments, that are base64 encoded strings through a message object. Here is the example code: 

    class Message < ActiveRecord::Base
      accepts_nested_attributes_for :attachments
    end 

    class Attachment < ActiveRecord::Base
      # document_id: string
      # document_filename: string
      # document_size: integer
      # document_content_type: string
      # message_id: integer

      CONTENT_TYPES = [
        "image/jpeg",
        "image/png",
        "image/gif",
        "text/plain",
        "application/pdf"
      ]

      attachment :document, content_type: CONTENT_TYPES

      # overriding document= provided by Attachment.attachment
      # document needs to be converted from a base64 encoded string to a StringIO object
      def document= encoded_string
        __send__("document_id_will_change!")
        super(StringIO.new(Base64.decode64(value)))
      end
    end 

If I try to create a message in my controller's create action with the following json, I will receive validation errors, and no records will be created. (The Refile::Attacher's record will have all nil attributes)
    
    { 
        text: "example",
        attachments_attributes: [
           { document_filename: "example.jpg", document_content_type: "image/jpeg", document: "base64" }
        ]
    }

If I replace the content_type definition with a generic rails validation for inclusion uploading works as expected. See below.

    validates :document_content_type, inclusion: { in: DOCUMENT_CONTENT_TYPES }
    attachment :document

This seems like there is a behavior problem when trying to validate content_types on nested attributes. (I also ran into this issue on the most recent version of master using accepts_attachments_for) Let me know if you need any more information when squashing this bug.

**Comment by abitdodgy** [comment]
I'm curious, why are you using `accepts_nested_attributes_for` and not `accepts_attachments_for` ?

**Comment by tomciopp** [comment]
accepts_attachments_for has not been released as part of the gem yet. It is defined in lib/refile/attachment/active_record.rb and was not included in the 0.5.5 (most recent) release. I am not comfortable using a git reference in my Gemfile, as I have done that before and it leads to bigger problems. The documentation or the gem should be updated to reflect that fact.

**Comment by jnicklas** [comment]
The documentation is up to date. If you're reading the documentation on GitHub you're reading the documentation of the master branch. You can read the documentation of the latest gem release [here](http://www.rubydoc.info/gems/refile).

As for this issue: you can't really use the provided content-type validation like this. The content-type is inferred from the uploaded file, not from the field value of `document_content_type`. Since what you're uploading is just a StringIO, Refile cannot infer its content type. The logic for this is [here](https://github.com/refile/refile/blob/master/lib/refile.rb#L211-L221). If you want to do things this way, then the inclusion validation is fine, and probably exactly what you want.
