### ISSUE TITLE
Image Preview

### ISSUE THREAD

**Issue by ibnukamy** [refile/refile#285]
Hi there, i'm new with the refile gem. Is the an image preview functionality built in refile helpers? I cannot find in the docs.

Thanks in advance.

**Comment by abitdodgy** [comment]
Not sure, how you missed it, but it's under the Rails Helpers section: :smile: 

https://github.com/refile/refile#4-rails-helpers

**Comment by abitdodgy** [comment]
Generating images is under the Rails Helpers section, linked below. But if by preview you mean an image preview when uploading, then I don't think so. But I think it's easy enough to write some JavaScript to do that. You should be able to get the URL of the upload from the form field and display it.

https://github.com/refile/refile#4-rails-helpers

**Comment by janko-m** [comment]
Yes, JavaScript image preview is not something Refile can do for you, because it wouldn't know where to put it, and how exactly you want it. And with JavaScript's File API it's really easy to do, see [this StackOverflow answer](http://stackoverflow.com/a/4459419/988414).

**Comment by ibnukamy** [comment]
Thanks guys. I found the javascript filereader solution. :+1:

**Comment by timurvafin** [comment]
@janko-m could we get image preview based on cached version?

**Comment by janko-m** [comment]
@timurvafin Unfortunately, that's not possible, because with the new secure URLs only the server can generate a URL to the image, so it wouldn't be possible without refreshing the page (and then you lose the info about the cached file). If you're uploading images, you can very easily do image previews with JavaScript when the user chooses a file in the filepicker, independently of Refile.
