### ISSUE TITLE
sometimes some images don't show up

### ISSUE THREAD

**Issue by medBouzid** [refile/refile#299]
![refilebug](https://cloud.githubusercontent.com/assets/3638022/8703209/0bc2e1de-2b14-11e5-8551-48fa30855e79.png)
I am iterating through all my images **@images = Image.all** 

    <% @images.each do |img| %>
        <%= image_tag attachment_url(img, :image, :limit, 250, 250), class: "img-lib" %>
    <% end %>

and it works fine, but sometimes some images don't appear and are replace by the "alt" attribute
When I inspect with firebug the image is there (loaded) but not show up !!

In my Image example there are 2 missing images which have the alt="Image"

**Comment by abitdodgy** [comment]
@medBouzid  I think it could be a mime-type issue, or you are not storing the file content_type in the DB.

**Comment by medBouzid** [comment]
@abitdodgy  the file content_type in the DB ?
I used PUMA server instead of WEBrick and that solved the issue in my local machine.
I think using CDN in the production will work also good in the production.
Thanks!

**Comment by janko-m** [comment]
When you open the URLs of the images that aren't showing in a separate tab, do they show? Are there any errors in the logs?

**Comment by medBouzid** [comment]
@janko-m when I check the image on "firebug source" it appears there but in the page it doesn't. There are no error log ! 
Someone told me to try Puma instead of WEBrick then when I did that, the problem was fixed... I don't know why exactly.

**Comment by janko-m** [comment]
Actually, I think I know what the problem was. WEBrick is single-threaded, which means that it can only process one request at the time. When your browser tries to request the images in parallel, these requests are processed one at a time, and it could happen that the browser just gives up when images take too long to load. Puma can by default process multiple requests in parallel, that's why it succeeds. That's my guess :)
