### ISSUE TITLE
ActionController::RoutingError (No route matches [POST] "/attachments")

### ISSUE THREAD

**Issue by svonborries** [refile/refile#306]
Hello All,

Thanks for the great job with this gem! It's my first time with refile gem, and is very simple to use, and very well documented.
I'm having some issues trying to use the "direct: true" option for the javascript, everything works great, but when i use this options rails throws this error:

Started POST "/attachments?locale=es/cache" for ::1 at 2015-07-22 23:15:18 -0400

ActionController::RoutingError (No route matches [POST] "/attachments"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'

I have a scope for all my routes, for multilanguage porpose:

scope "(:locale)", locale: /es|en/ do
    #inside this scope are all my routes
end
I'm using Ruby 2.1.1 and Rails 4.2.0
Is there some kind of issues using scopes in routes file?
Just for the records... everything works great, i can upload and download files, actually i'm using it with cocoon gem (explicit requirement of my customer), but when trying to use the javascript option the above error appears, Am I missing something here? please any help is always welkome!

**Comment by janko-m** [comment]
Where did you mount you Refile app? You disabled `automount`, right?

**Comment by trentclowater** [comment]
Disabling `automount` and adding the route manually doesn't help. The problem is that when you override the `default_url_options` method in a controller the `attachment_field` helper adds the url options into the `data-url` field when using `direct: true`, resulting in an incorrect path like in the example given by @svonborries above where the query string is added in the middle of the path, and resulting in failure when doing direct uploads. (I ran into the exact same problem when adding locales, which is how I ended up here.)

The pull request by @maurogeorge that referenced this issue came up with the same solution I did for this problem, so I would give my vote for merging this if there are no side effects and after fixing any failing tests.
