### ISSUE TITLE
How to protect presign object?

### ISSUE THREAD

**Issue by TangRufus** [refile/refile#338]
Using refile with a s3 backend (store & cache)
I see that site.com/attachments/cache/presign returns a presign object (JSON) to everyone. 

1. Is this secure? 
Seems everyone could request the presign object, and upload to the cache backend. 

2. How can I add authentication (pundit / cancancan) to this endpoint?

3. How can I customized the presign object? Adding acl, shorten expire time, etc 

Thanks!!

**Comment by fabn** [comment]
@jnicklas I absolutely second first point, while if well configured cache backend will expire its content, it's still not advisable to allow everyone to upload what they want, especially when using S3 as backend since that will cost money.

Also I'd add point 1b to the previous list, i.e. one can upload to the cache whatever he wants by using (for instance) curl with

```
curl -XPOST -v localhost:3000/attachments/cache -F 'file=@Gemfile'
```

If for whatever reason cache folder is exposed in the public folder (a la carrierwave) this would be a serious issue.

I'd start to think to a default way of authenticate these kind of requests and to make the default authentication block to return false. In this way any refile user will need to think on how to authenticate upload requests.

Alternatively, since the upload endpoint is only needed for the javascript helper, I'd disable it by default.

What do you think?

**Comment by fabn** [comment]
@TangRufus here's a quick and dirty monkey patch to authenticate any upload request, put it into refile initializer and change the authentication logic to match your environment (I'm using Devise+CanCan with an `AdminUser` model)

```ruby
module RefileUploadAuthentication

  # Redefine upload allowed, super is available because of Module#prepend
  def upload_allowed?
    super && can?(:create, Picture)
  end

  private

  # Mimic devise current user method and make it available in the above checks
  # @see https://github.com/hassox/warden/wiki/Authenticated-session-data
  def current_user
    warden = env['warden']
    warden.user if warden.authenticated?(:admin_user)
  end

  # Mimic CanCan helper for checking permissions
  def can?(*args)
    (@_ability ||= AdminAbility.load_ability(current_user)).can?(*args)
  end

end
# Patch refile app with the authentication method for upload
Refile::App.prepend(RefileUploadAuthentication)
```

**Comment by jnicklas** [comment]
"Secure" is pretty relative here. There is no way to exploit this maliciously other than uploading lots of files, which while costing you money isn't really terribly useful to an attacker. It's worth considering though that any kid of app where your users can sign up freely and access upload functionality *inherently* has the same problem. Adding authentication in that case does nothing. It's super easy to take the session cookie and copy it into the console and continue running CURL. The only kind of app where this matters is one where sign up is closed off. Given that lots of people build applications all the time which allow open sign ups and file uploads, it seems that they are comfortable with exposing upload functionality.

That being said, it seems doable to add the same kind of cryptographic protection that we already have for GET requests, which would probably still not be perfect, but better than the status-quo.

If you're not comfortable with this, it's pretty easy to disable this functionality entirely or to wrap it in some kind of other authentication scheme. If you have Warden anyway, why not wrap the Refile app in a middleware which does the authentication? Easier and more stable than monkey-patching the Refile app.

Regarding the third question, we don't currently provide any way of configuring the presign object, though I'd certainly be open to doing this kind of thing.

**Comment by fabn** [comment]
> "Secure" is pretty relative here. There is no way to exploit this maliciously other than uploading lots of files, which while costing you money isn't really terribly useful to an attacker. It's worth considering though that any kid of app where your users can sign up freely and access upload functionality inherently has the same problem.

In my opinion there are two issues here:

The first is about all cms like applications where authenticated users provide content and guest users just read it. For these kind of applications a guest user should not be able to upload anything thus upload authentication is a must.

The second issue is about consequences of untrusted uploads, in the case of S3 backends, as already discussed earlier, it will cost money. With filesystem backends the upload endpoint may be used for a denial of service attack, a malicious user can potentially fill up an hard drive with lot of huge files taking down a server in minutes.

> Adding authentication in that case does nothing. It's super easy to take the session cookie and copy it into the console and continue running CURL. The only kind of app where this matters is one where sign up is closed off. Given that lots of people build applications all the time which allow open sign ups and file uploads, it seems that they are comfortable with exposing upload functionality.

That's correct, it's pretty hard to limit uploads in a reliable (and generic) way, for this reason I think that a definitive solution to the issue does not belong to this gem. However refile gem should provide an extension point to allow the hosting application to enforce authentication and/or rate limiting.

A solution I like is the one provided by [comfortable mexican sofa cms](https://github.com/comfy/comfortable-mexican-sofa/wiki/Changing-default-authentication) (which is in some way similar to the monkey patch above). They provide [config accessors](https://github.com/comfy/comfortable-mexican-sofa/blob/b7472df401fc5a0db01e8391a4557e8a58777747/lib/comfortable_mexican_sofa/configuration.rb#L12:L22) for authentication modules, [default implementation](https://github.com/comfy/comfortable-mexican-sofa/tree/0ebcba38fecc48a557d351c509b49427cdb8ebae/lib/comfortable_mexican_sofa/access_control) which essentially is a noop for the public part, and finally they [mix in](https://github.com/comfy/comfortable-mexican-sofa/blob/4cd82f3f333c76a78714da617f471592418d600e/app/controllers/comfy/admin/cms/base_controller.rb#L5:L9) the configured modules in their controllers.

In this way it would be easy for any hosting app to do whatever they want to protect uploads (and potentially downloads) in the context of the `Refile::App` having access to request, session and whatever.

What do you think? Would you accept a such pull request?

> If you're not comfortable with this, it's pretty easy to disable this functionality entirely or to wrap it in some kind of other authentication scheme. 

How to do that without monkey patching?

> If you have Warden anyway, why not wrap the Refile app in a middleware which does the authentication? Easier and more stable than monkey-patching the Refile app.

That was my first thought, however [devise authenticated constraint](https://github.com/plataformatec/devise/blob/181920886e4e60783f330b94072b0423345f714f/lib/devise/rails/routes.rb#L289) does not provide request in the block, only the user. If I constraint the whole refile application in an `authenticated` block then  unauthenticated user won't be able to see images because refile app contains all the endpoints including the download ones.

**Comment by jnicklas** [comment]
> How to do that without monkey patching?

To disable (on master): `Refile.allow_uploads_to = []`

To wrap it in authentication, just create a middleware and wrap it around. You should be able to do pretty much the same you did in your monkey patch, only in a middleware.

**Comment by jnicklas** [comment]
I'm closing this issue for now. While it would be nice to add cryptographic authentication to these actions to protect them, doing so is outside of my expertise when it comes to crypto.

I think we'd have to design something similar to Amazon's own presign scheme, and I'm not confident I can get that right. If someone were to attempt to do this, I'd like to be confident that their cryptography skills are strong enough that they can design an implementation which is safe against possible side-channel attacks. This kind of crypto is a *lot* harder than the simple HMAC signature verification we do on GET requests.

I've created #352 to track that we should add some documentation on how to wrap the application in authentication middleware.
