### ISSUE TITLE
Presence validation for #{name}_id interferes with attacher.store!

### ISSUE THREAD

**Issue by monkbroc** [refile/refile#355]
I wanted to make sure a file is always attached to the model so I used this validation:

```ruby
class Attachment < ActiveRecord::Base
  attachment :file
  validates_presence_of :file_id, :file_filename, :file_size, :file_content_type
end
```

When I save an Attachment, it fails because the file_id is empty, but the other attributes are filled in. I figured out that the `attacher.store!` method called in a `before_save` hook is supposed to set the `#{name}_id`.

Removing the `file_id` presence validation works around the issue.

How would you make sure that a file is always present?

**Comment by abitdodgy** [comment]
I would deal with this via a database constraint. There should be no circumstance where the file id is missing because of user input, and errors in user input is what validations are meant to catch. In this case I would want a failure, not a validation error. If the `file_id` is missing it's likely because of a bug, and not something that the user has done, so giving the user feedback about the error doesn't really gain you anything.

**Comment by jnicklas** [comment]
You should  just be able to:

``` ruby
class Attachment < ActiveRecord::Base
  attachment :file
  validates_presence_of :file
end
```

**Comment by abitdodgy** [comment]
I take that back, actually. There obviously are circumstances when this could happen. My thinking was so ingrained in my current use of Refile that I've forgotten about obvious scenarios.

**Comment by monkbroc** [comment]
`validates_presence_of :file` leads to some quirks. I'll close this and we can continue the discussion in PR #359.
