### ISSUE TITLE
file.id based on parent model id

### ISSUE THREAD

**Issue by rafaltrojanowski** [refile/refile#375]
Is possible to create custom hasher that generates id based on record id instead random string?

**Comment by jnicklas** [comment]
This is explicitly not possible. The reasoning is that it makes caching much harder, because the same record could have multiple files (when updated) and you wouldn't be sure which file is actually meant, since they have the same id. Also it poses a problem for direct uploads, since you won't know the id of the record at the time the file is uploaded because it might not have been created yet.
