### ISSUE TITLE
Doubled format in attachment url if I specified the filename

### ISSUE THREAD

**Issue by asiniy** [refile/refile#381]
Just noticed one small bug.

I set up a refile for uploading documents (.pdf & .docx).

I store both `resume_id` and `resume_filename` columns in my postgres: `attachment :resume`. I loaded file to my `rails 4.2.4` application via usual `file_field_tag`.

I uploaded the file: `CV.pdf`. Now I see `resume_filename` in my model is equal to `CV.pdf`. As predictable.

Now I create a link:

```
= link_to 'Resume', attachment_url(user, :resume)
/attachments/548c27801c70859834d7ad6a1a1984f4bb550e7e/store/fe03728a04a687ee0327fd49f191e6105743854b4c803c792f42cdd6f889/CV.pdf
```

All is cool. But if I specify resume_filename, I get

```
= link_to 'Resume', attachment_url(user, :resume, filename: user.resume_filename)
/attachments/548c27801c70859834d7ad6a1a1984f4bb550e7e/store/fe03728a04a687ee0327fd49f191e6105743854b4c803c792f42cdd6f889/CV.pdf.pdf
```

I get link to `CV.pdf.pdf` which is opened and works well, but little unpredictable. I think this is a small bug.

**Comment by abitdodgy** [comment]
I had this issue, and I looked at the source code before filing a bug report. [It happens here][1], where format gets appended to the final result. The reason I did not file a bug report is because I think this *might* be the expected behaviour, but I'm not sure. Maybe @jnicklas can clarify.

```ruby
file_url(file, *args, host: host, prefix: prefix, filename: filename, format: format)
```

Anyway, for the time being, solving this is fairly easy:

```ruby
class User
  def resume_filename_without_extension
    File.basename resume_filename, '.*'
  end
end
```
```
link_to 'Resume', attachment_url(user, :resume, filename: user.resume_filename_without_extension)
```
  [1]: https://github.com/refile/refile/blob/90cbf2ac808b37dd5ce87104171499db07d6e522/lib/refile.rb#L391

**Comment by jnicklas** [comment]
It is somewhat tricky given an arbitrary filename to extract which part of the file is the extension and which isn't. For examples, files could be named any of:

- something.zip
- some.thing.zip
- some.t.zip
- file.something.foo.tar.gz
- f.tar.gz
- Rakefile
- Something.withoutanextension

And so on and so forth. Which part of the filename is the extension? There's no really good answer.

Since we infer the extension from the content type if it's given we end up with something like this:

``` ruby
file_url(file, filename: "test.gif", format: "jpg")
```

I think there's no sane way to make that return `test.jpg` rather than `test.gif`.

The best I can think of is to strip the file extension in the first place, based on the original content type of the file, but that might be kinda tricky to implement.

So in a sense it's expected behaviour, because filenames are weird. But it'd also be nice if the default case would be somewhat nicer.

**Comment by choonkeat** [comment]
>> I get link to CV.pdf.pdf which is opened and works well, but little unpredictable. I think this is a small bug.

> The best I can think of is to strip the file extension in the first place, based on the original content type of the file, but that might be kinda tricky to implement.

how about something like

``` diff
diff --git a/lib/refile.rb b/lib/refile.rb
index f7da271..1f1ff3b 100644
--- a/lib/refile.rb
+++ b/lib/refile.rb
@@ -313,7 +313,7 @@ module Refile
       backend_name = Refile.backends.key(file.backend)
 
       filename = Rack::Utils.escape(filename)
-      filename << "." << format.to_s if format
+      filename << "." << format.to_s if format unless filename.downcase.end_with?(format.to_s.downcase)
 
       base_path = ::File.join("", backend_name, *args.map(&:to_s), file.id.to_s, filename)
 
```
