### ISSUE TITLE
Different max size for different attachments/models

### ISSUE THREAD

**Issue by leifcr** [refile/refile#387]
Is it be possible to have different max_size for different attachments?

The setting is currently on the backend, which is set for all attachement types.

example
``` ruby
class Post
  attachment :image # Should be less than 20 megabytes
end

class VideoTutorial
  attachment :video # Should be less than 250 megabytes
end
```

Setting a max_size on the backend to 250 will allow images to be larger than 20, and setting max_size to 20 will not allow large enough videos.

This is similar to the request for setting per-attachemnt max_size in PR #193

**Comment by abitdodgy** [comment]
You can use a validator for that. It's not completely dependable, since Refile relies on the client for file size, but in most cases it should be fine.

For example:

```
validates :profile_image_size, numericality: { less_than_or_equal_to: 0.5.megabytes }, allow_blank: true
```

This assumes that you have the `profile_image_size` column in your database, and your attachment declaration is `attachment :profile_image`.

**Comment by leifcr** [comment]
The solution was a lot easier thatn I first thought of. I guess I was over-complicating things...
