### ISSUE TITLE
Multiples Stores

### ISSUE THREAD

**Issue by felipewmartins** [refile/refile#390]
Hello,
 Is it possible to have more than one store in refile ?

**Comment by felipewmartins** [comment]
? :)

**Comment by sobrinho** [comment]
You can probably write your own backend that does that ;)

**Comment by jnicklas** [comment]
Do you mean as in Store files in multiple backends? It should be fairly easy to do by writing a backend which composes multiple backends. I think this would actually be quite useful, and should be reasonably simple to do.

**Comment by taylorbrooks** [comment]
@jnicklas I originally thought it would be possible to support multiple backends by setting within the class, like this:

```ruby
class Person
  attachment :profile_pic, 
    cache: S3BackendSetter.new("bucket-for-profile-pics").cache, 
    store: S3BackendSetter.new("bucket-for-profile-pics").store
end

class Import
  attachment :csv, 
    cache: S3BackendSetter.new("bucket-for-csvs").cache, 
    store: S3BackendSetter.new("bucket-for-csvs").store
end

class S3BackendSetter
  def new(bucket)
    @bucket = bucket
  end

  def cache
    Refile::S3.new(prefix: "cache", **aws_settings)
  end

  def store
    Refile::S3.new(prefix: "store", **aws_settings)
  end

  def aws_settings
    {
      access_key_id: ENV["AWS_ACCESS_KEY"],
      secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
      region: "us-east-1",
      bucket: @bucket,
    }
  end
end
```

But I learned something interesting about Ruby. The [default arguments](https://github.com/refile/refile/blob/master/lib/refile/attachment.rb#L38) on `attachment.rb` in Refile are symbols.

So if you do:
```ruby
def hi(foo: :bar)
  p foo
end

# $ hi
# $ => :bar
# $ hi("baz")
# $ => ArgumentError: wrong number of arguments (1 for 0)
```

So it seems that as long as `attachment.rb` is disallowing `cache/store` to be set dynamically AND you set `Refile.cache` or `Refile.store` as class vars (not thread-safe), instead of instance vars (thread-safe), it's not possible to use multiple backends without a major re-write of the gem.

Maybe I'm missing something obvious, but those were my initial findings. I'm happy to help/contribute on allowing multiple backends. I would just need to know what strategy you prefer @jnicklas.

**Comment by jnicklas** [comment]
@taylorbrooks the original issue is about something entirely different: using multiple backends *at the same time*, which is quite different from using different backends for different models. The latter is already supported by Refile, and actually quite easy to do:

Register the backend with:

``` ruby
# note that the key should be a String, not a Symbol!
Refile.backends["my_cache"] = SomeBackend.new("...")
Refile.backends["my_store"] = SomeBackend.new("...")
```

And then use your backend like this:

``` ruby
class Person
  attachment :profile_pic, cache: "my_cache", store: "my_store"
end
```

**Comment by taylorbrooks** [comment]
@jnicklas Yeah, I'm a bonehead. I just realized I was my `S3BackendSetter` didn't have an `#initialize` method and was throwing that error.

I should write more tests. Thanks for the great gem!

**Comment by sobrinho** [comment]
I like the idea but think in that:

``` ruby
# Regular backends
backend1 = SomeBackend.new("...")
backend2 = SomeBackend.new("...")

# A "composable backend" that receives any number of stores and perform the actions in all of them
Refile.backends["reliable_store"] = ComposableBackend.new([backend1, backend2])
```

There are questions like:

1. What happens if one store fails to store?
2. What if the store that fails is the latest one?
3. Would we need to delete the file from the previous stores?
4. How to guarantee something like a "transaction" to avoid these issues?
5. What about the performance of this since we are going to communicate with more than one remote store (assuming that)?

I see this being a complex feature to Refile, maybe an external gem to support that.

Although thinking in large-scale applications, doing this synchronously may be an issue because of performance and failures.

Since I see no easy way to go on this, I'm going to close.

Feel free to point at the Wiki some solution if you find or develop any ❤️
