### ISSUE TITLE
[OT] Looking for the Google Group Admin(s) for CarrierWave

### ISSUE THREAD

**Issue by walterdavis** [refile/refile#445]
If you know who that is, could you send them my way? There's been a nasty rash of recruiter spam there lately, and I would like to volunteer to moderate/ban until it goes away. There's a lot of good information in that list that is being diluted or polluted.

Thanks,

Walter Davis

**Comment by janko-m** [comment]
Yeah, I saw it, it's pretty bad. But maybe you should open this issue on CarrierWave.

**Comment by jnicklas** [comment]
I am the owner of that group.

@walterdavis I've made you moderator of the group. I think that means you should be able to remove any spam and also change posting settings. At some point I opened up the group entirely because I didn't want to moderate it anymore, feel free to enable post moderation if you want to.
