### ISSUE TITLE
CDN cache invalidation

### ISSUE THREAD

**Issue by hughfm** [refile/refile#481]
I'm curious if anyone has concerns about files hanging around in a CDN cache after they have been deleted from the app. Has anyone implemented an invalidation strategy for this purpose? 

My concern is that with Refile's default settings and the recommended CDN setup, files will remain accessible at their CDN urls for up to a year after they have been deleted. 

Anyone have any thoughts on this?

**Comment by mmplisskin** [comment]
This really shouldn't be an issue with cloudfront or even other cdns.. you could just invalidate everything through them occasionally.

**Comment by hughfm** [comment]
Thanks @mmplisskin, have you found Cloudfront tends to remove things aggressively, due to low traffic, or similar? 

I think invalidating the whole cache kind of defeats the purpose of the far-future expiries, and it would probably make more sense to drop the expiry times down from the default 365 days to something more immediate, however this is going to impact application performance as a whole and the Refile docs seem to make a point of trying to avoid streaming files through the application whenever possible. 

I understand this issue totally depends on the types of files you are storing, and for many applications it wouldn't be an issue. However, for an end user who deletes a file with some sort of sensitive info, they are likely to be concerned to discover the generated link still works. 

Perhaps the reliance on a CDN makes Refile not the best choice for certain types of 'private' files...

**Comment by jnicklas** [comment]
It depends on how you define private. Since the filenames are not possible to guess, no one without a URL will be able to access them. If you want to time limit them, it is probably best to use time limitted CDN urls.

From what I understand creating invalidations is generally discouraged with most CDNs except in special circumstances.

**Comment by hughfm** [comment]
Thanks for the response @jnicklas. I understand and agree that the URL strategy ensures the files are private. My concern here is specifically with users having control over the availability of files after they have been shared. As a user, if I upload a file, share the URL and then at some point in the future delete that file, I would be surprised to learn that the URL I have shared is actually still usable, and will remain so in some cases for up to a year. 

My feeling is that this is why CDNs are more suitable for static assets like images and stylesheets than files that users need to have control over, in terms of their availability. 

I'd be interested to hear why creating invalidations would be discouraged? I have now implemented an invalidation strategy with Cloudfront whereby stale URLs are invalidated when files get changed or removed by my Refile model. This seems to be a reasonable solution to me, but would love to hear any opposing views. 

To be clear, I've really enjoyed using Refile and don't consider this a Refile issue per se. More just understanding the limitations of relying on a CDN for certain types of use cases.

**Comment by sobrinho** [comment]
Well, there is a lot of options here.

You can integrate with your CDN to be able to expire the asset, you can do that in Amazon CloudFront by expiring a specific path (even with wildcards).

Another option is to reduce the expiration time to a value that makes sense for your application like 24 hours or 7 days and warns the user that the file may be still available until that time (like when you unsubscribe from a mailing list and they say that will take at least 7 days to be unsubscribed).

But if your data is really sensible, you may have to use a completely different approach like serving the asset through your application (isn't easy to scale that but is like more secure, less scalable).

Since there is more than one year without interactions here, I will be closing.

Feel free to create a wiki page explaining the pros and cons of each approach, if you want.

Thanks! ❤️

**Comment by hughfm** [comment]
Thanks for the response @sobrinho - I did end up implementing an integration with the CDN as you suggest 👍🏻 this is no longer something I'm working on regularly so I don't think I'll have time to write up a wiki page. Great to see Refile will continue to get some attention though! Cheers.
