### ISSUE TITLE
Image dont render when using FILL option

### ISSUE THREAD

**Issue by 90caiosantos** [refile/refile#506]
Hey guys

When i use:

`<%= attachment_image_tag(image, :image) %>`

My image render with no problem with this link:
http://192.168.10.2:3000/attachments/1716733fde74e4bcd9f1d579cad24648e24a538a/store/8c8a173eb6c9b5b6a0955f265a5cc64a0618a929e56b27ffd7141ebe1d1c/image

but when i use 

`<%= attachment_image_tag(image, :image, :fill, 300, 300) %>`

my image dont render in my app

when i try to open the url i get this message => error

can anyone help me with that?

**Comment by goodviber** [comment]
I think fill requires imageMagick, you can install it on your system/server with

brew install imagemagick # OS X
sudo apt-get install imagemagick # Ubuntu

as per the docs

**Comment by conwayanderson** [comment]
I'm having the same problem right now

**Comment by goodviber** [comment]
@conwayanderson have you resolved this?

**Comment by conwayanderson** [comment]
@goodviber I have - tl;dr I believe it's most likely due to user error.

The model/db references seem like they weren't properly set up. This might have prevented certain parts of imagemagick from working.

As a beginner, this tutorial helped isolate where I'd set things up incorrectly: http://codely.me/ruby-on-rails/create-photoblog-uploading-multiple-images-in-rails-4-using-refile-gem/. IMO it'd be worth adding a link to this tutorial and/or having a separate refile example app that goes through everything step by step. Happy to put in a PR request for that but figured it'd seem like I was promoting a specific person's tutorial.

**Comment by sobrinho** [comment]
Thanks, closing.
