### ISSUE TITLE
remote forms doesn't work after upload:complete event

### ISSUE THREAD

**Issue by kdiogenes** [refile/refile#58]
When you try to submit a form with `remote: true` jquery-ujs checks if it's had any non blank file inputs https://github.com/rails/jquery-ujs/blob/master/src/rails.js#L422, so the remote option is ignore and the form is submitted with a normal POST.

My solution was to modify the if in this line https://github.com/elabs/refile/blob/master/app/assets/javascripts/refile.js#L37 to:

``` javascript
if((xhr.status >= 200 && xhr.status < 300) || xhr.status === 304) {
  var id = input.getAttribute("data-id") || JSON.parse(xhr.responseText).id;
  input.previousSibling.value = id;
  input.removeAttribute("name");
  input.value = ''; // <-- included this
  dispatchEvent("upload:success", xhr.responseText);
}
```

This make the input file empty, so for jquery-ujs all the file fields are blank and the form is submitted remotely.

I will be happy to make a pull request if this approach is considered correctly.

**Comment by danieldocki** [comment]
I'm the same problem =\

**Comment by danieldocki** [comment]
This gem https://github.com/JangoSteve/remotipart resolved the problem with upload file with remote: true

**Comment by JoshuaNovak919** [comment]
Is there any way to get this to work properly? I tried @cerdiogenes code and it didn't work.

**Comment by masonhale** [comment]
@danieldocki I looked at the remotipart gem. I wouldn't use it. It is looking very long in the tooth and somewhat neglected. I'm paranoid about adding too much magic, especially when it involves adding new middleware to my stack. Seems like overkill anyway to work around this issue as it triggers submitting forms through a hidden iframe, which is not longer needed thanks to refile! Keep it simple.

We just need some way to tell Rails UJS to not count refile handled file inputs when determining whether to abort the AJAX form submission.

I poked around through the remotipart gem to see how it works. I found it relies on handling the `ajax:aborted:file` event fired by Rails UJS when it aborts due to non-empty file inputs.

I was able to come up with the event handler below which tells Rails UJS to proceed with submitting the form via Ajax if all the non-empty file inputs are associated with refile.

I used the `data-reference` attribute to detect the presence of refile handling. @jnicklas:  is that a safe bet?

```javascript
$(document).on('ajax:aborted:file', 'form', function(){
  var form = $(this);
  // if all non-blank file inputs are handled by refile,
  // then resume
  var nonBlankFileInputs = $.rails.nonBlankInputs(form, $.rails.fileInputSelector);
  if (nonBlankFileInputs.filter(':not([data-reference])').length === 0) {
    $.rails.handleRemote(form);
    return false;
  } else {
    return true;
  }
});
```

**Comment by jnicklas** [comment]
@masonhale I think that's a fine workaround. Someone (not me ;)) should really patch rails_ujs to do the right thing though.

**Comment by masonhale** [comment]
@jnicklas I was thinking about how to patch rails_ujs, and it occurs to me that it needs some way to know which file input fields should be excluded from its check of non-blank file inputs. I would propose that it looks for some specific attribute on the input as a flag to indicate it should be ignored. Something like `data-rails-ajax-ignored=true`. This way an application author could manually add the attribute to exclude it from the file input check (and potentially the separate required field input check), and rails-friendly file upload libraries like refile could potentially add the ignore attribute automatically to help make things work automatically. Any thoughts?

**Comment by jnicklas** [comment]
No, the reason for exclusion should be that the field is disabled. Disabled fields aren't submitted by browsers, rails_ujs shouldn't care that there's a disabled field with a file attached in the form.

**Comment by masonhale** [comment]
@jnicklas thanks for the clarification. I didn't realize Refile disabled fields and that would be a good method to filter file input fields. Question: when does this disabling happen? Is it possible the rails_ujs script could fire before Refile sets the field to disabled? 
@jnicklas Looking more closely at how the refile.js operates, I notice it removes the name of the input field after the file is processed [here](https://github.com/refile/refile/blob/07165d5adc03e8c83b2014bcf0d4ae1d4c56e440/app/assets/javascripts/refile.js#L107). I don't see where it sets the input file to disabled. Am I missing something? It makes me wonder if ignoring file inputs with no name attribute would work as well or better than ignoring disabled fields? (To be clear, I'm asking for clarification because I intend to submit a PR to fix rails_ujs. Thanks for the help).

PS: Thanks also for all the work you've put into Refile. I think it is really great work and I am very thankful you've put in the effort and hard-won experience to make it. Thank you!

**Comment by jnicklas** [comment]
@masonhale uuhh I was remembering it wrong. We do indeed remove the name to not submit the field. Browsers don't submit it, so rails_ujs should not accout for it, but it does.

**Comment by masonhale** [comment]
Ok, based on what I've learned by working on a Rails UJS patch, I've come up with a better/simpler monkey-patch to get Refile and Rails UJS working together. This avoids having to catch the aborted file event. Much cleaner. It simply tweaks the fileInputSelect UJS uses to make sure the input has a name. (Interestingly, Rails UJS already has a similar check in place for required fields).

```javascript
// run this anytime after rails / jquery-ujs is loaded
$.rails.fileInputSelector = 'input[name][type=file]';

```

**Comment by jokklan** [comment]
@jnicklas actually does Rails UJS not include disabled inputs since v. 1.1.0 (https://github.com/rails/jquery-ujs/pull/430). Could we patch refile to disable the input instead of just removing the name attribute?

**Comment by jnicklas** [comment]
@jokklan no this does not work. Disabling the input not only has a visual effect we do not want, but it also prevents the user from selecting another file for upload.

**Comment by jnicklas** [comment]
It's really a simple fix in Rails UJS, which they should make anyway, someone should really submit a patch. It's not going to be me though, since I don't actually ever use rails_ujs ;)

**Comment by masonhale** [comment]
I just submitted a pull request to jquery-ujs for this issue: https://github.com/rails/jquery-ujs/pull/464

I meant to do it before the holidays, but got busy/distracted and didn't get back to it.

**Comment by jnicklas** [comment]
You're a hero @masonhale! :smile:

**Comment by danieldocki** [comment]
@masonhale :metal:

**Comment by masonhale** [comment]
@danieldocki @jnicklas Can you do a favor and comment on the jquery-ujs pull request I opened to draw more attention to it? https://github.com/rails/jquery-ujs/pull/464

**Comment by jnicklas** [comment]
@masonhale I added a comment. It's not been that long though, OSS moves slowly ;) They'll get to it eventually.
